import type { PermissionId } from '../types/contract.types';

export const PERMISSION_REGISTRY: readonly { permission_id: PermissionId; domain: string; business_action: string }[] = [
  { permission_id: 'org.create', domain: 'Organizational', business_action: 'Create Organization' },
  { permission_id: 'org.update_profile', domain: 'Organizational', business_action: 'Update Profile' },
  { permission_id: 'org.elevate_status', domain: 'Organizational', business_action: 'Elevate Status' },
  { permission_id: 'org.read', domain: 'Organizational', business_action: 'Read Organization' },
  { permission_id: 'person.create', domain: 'Person', business_action: 'Create Person' },
  { permission_id: 'person.update', domain: 'Person', business_action: 'Update Person' },
  { permission_id: 'person.mutate', domain: 'Person', business_action: 'Mutate Person' },
  { permission_id: 'person.assign', domain: 'Person', business_action: 'Assign Person' },
  { permission_id: 'person.read', domain: 'Person', business_action: 'Read Person' },
  { permission_id: 'person.update_family', domain: 'Person', business_action: 'Update Family' },
  { permission_id: 'person.update_competency', domain: 'Person', business_action: 'Update Competency' },
  { permission_id: 'pastoral.create', domain: 'Pastoral', business_action: 'Create Pastoral' },
  { permission_id: 'pastoral.update', domain: 'Pastoral', business_action: 'Update Pastoral' },
  { permission_id: 'pastoral.delete', domain: 'Pastoral', business_action: 'Delete Pastoral' },
  { permission_id: 'pastoral.read', domain: 'Pastoral', business_action: 'Read Pastoral' },
  { permission_id: 'schedule.create', domain: 'Pastoral', business_action: 'Create Schedule' },
  { permission_id: 'schedule.update', domain: 'Pastoral', business_action: 'Update Schedule' },
  { permission_id: 'asset.create', domain: 'Asset', business_action: 'Create Asset' },
  { permission_id: 'asset.update', domain: 'Asset', business_action: 'Update Asset' },
  { permission_id: 'asset.delete', domain: 'Asset', business_action: 'Delete Asset' },
  { permission_id: 'asset.read', domain: 'Asset', business_action: 'Read Asset' },
  { permission_id: 'asset.upload_attachment', domain: 'Asset', business_action: 'Upload Attachment' },
  { permission_id: 'territory.create_risk', domain: 'Territory', business_action: 'Create Risk' },
  { permission_id: 'territory.create_potential', domain: 'Territory', business_action: 'Create Potential' },
  { permission_id: 'territory.update', domain: 'Territory', business_action: 'Update Territory' },
  { permission_id: 'territory.upload_attachment', domain: 'Territory', business_action: 'Upload Attachment' },
  { permission_id: 'demography.upsert', domain: 'Demography', business_action: 'Upsert Demography' },
  { permission_id: 'demography.read', domain: 'Demography', business_action: 'Read Demography' },
  { permission_id: 'aid.create', domain: 'Aid Workflow', business_action: 'Create Aid' },
  { permission_id: 'aid.update', domain: 'Aid Workflow', business_action: 'Update Aid' },
  { permission_id: 'aid.submit', domain: 'Aid Workflow', business_action: 'Submit Aid' },
  { permission_id: 'aid.approve.step_1', domain: 'Aid Workflow', business_action: 'Approve Step 1' },
  { permission_id: 'aid.approve.step_2', domain: 'Aid Workflow', business_action: 'Approve Step 2' },
  { permission_id: 'aid.reject', domain: 'Aid Workflow', business_action: 'Reject Aid' },
  { permission_id: 'aid.resubmit', domain: 'Aid Workflow', business_action: 'Resubmit Aid' },
  { permission_id: 'user.create', domain: 'User & Security', business_action: 'Create User' },
  { permission_id: 'user.update_role', domain: 'User & Security', business_action: 'Update Role' },
  { permission_id: 'user.update_status', domain: 'User & Security', business_action: 'Update Status' },
  { permission_id: 'user.delete', domain: 'User & Security', business_action: 'Delete User' },
  { permission_id: 'user.update_own_profile', domain: 'User & Security', business_action: 'Update Own Profile' },
  { permission_id: 'user.toggle_biometric', domain: 'User & Security', business_action: 'Toggle Biometric' }
] as const;

export const PERMISSION_COUNT = PERMISSION_REGISTRY.length;
