-- Migration: 20260721_fix_kmj_quotes_bajem.sql
-- Description: Clean double quotes, seed missing KMJs from Jemaat.txt, add kategori (Bajem/Pos Pelkes) column to m_pos_pelkes

BEGIN;

-- 1. Add kategori column to m_pos_pelkes if not exists
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name='m_pos_pelkes' AND column_name='kategori'
    ) THEN
        ALTER TABLE m_pos_pelkes ADD COLUMN kategori VARCHAR(50) DEFAULT 'Pos Pelkes';
    END IF;
END $$;

-- 2. Update m_jemaat_induk (cleaned names & keterangan)
UPDATE m_jemaat_induk SET nama_induk = 'FILADELFIA', keterangan = 'Medan' WHERE id_induk = '01-03-FM';
UPDATE m_jemaat_induk SET nama_induk = 'ANUGERAH', keterangan = 'Pangkalan Brandan Langkat' WHERE id_induk = '01-01-AP';
UPDATE m_jemaat_induk SET nama_induk = 'BANDA ACEH', keterangan = 'Banda Aceh' WHERE id_induk = '01-02-BA';
UPDATE m_jemaat_induk SET nama_induk = 'EFATA', keterangan = 'Tanjung Morawa Deli Serdang' WHERE id_induk = '01-13-ET';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Medan' WHERE id_induk = '01-04-IM';
UPDATE m_jemaat_induk SET nama_induk = 'KASIH KARUNIA', keterangan = 'Medan' WHERE id_induk = '01-05-KM';
UPDATE m_jemaat_induk SET nama_induk = 'MARANATHA', keterangan = 'Pematang Siantar' WHERE id_induk = '01-06-MP';
UPDATE m_jemaat_induk SET nama_induk = 'MITRA PARSINGGURAN NAULI', keterangan = 'Parsingguran Humbang Hasundutan' WHERE id_induk = '01-12-MP';
UPDATE m_jemaat_induk SET nama_induk = 'PATMOS', keterangan = 'Sabang' WHERE id_induk = '01-07-PS';
UPDATE m_jemaat_induk SET nama_induk = 'PAULUS', keterangan = 'Binjai' WHERE id_induk = '01-14-PB';
UPDATE m_jemaat_induk SET nama_induk = 'PNIEL', keterangan = 'Kampung Kolam Deli Serdang' WHERE id_induk = '01-08-PT';
UPDATE m_jemaat_induk SET nama_induk = 'SILOAM', keterangan = 'Sibolga' WHERE id_induk = '01-09-SS';
UPDATE m_jemaat_induk SET nama_induk = 'SYALOOM', keterangan = 'Bangun Purba Deli Serdang' WHERE id_induk = '01-11-SB';
UPDATE m_jemaat_induk SET nama_induk = 'YOPPE', keterangan = 'Belawan Medan' WHERE id_induk = '01-10-YB';
UPDATE m_jemaat_induk SET nama_induk = 'MADUMA', keterangan = 'Medan' WHERE id_induk = '01-15-MD';
UPDATE m_jemaat_induk SET nama_induk = 'PIR BESITANG', keterangan = 'Pangkalan Brandan' WHERE id_induk = '01-16-PB';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Pekanbaru' WHERE id_induk = '04-10-IP';
UPDATE m_jemaat_induk SET nama_induk = 'ANUGERAH', keterangan = 'Sorek Pelalawan' WHERE id_induk = '04-01-AS';
UPDATE m_jemaat_induk SET nama_induk = 'BUKIT ZAITUN', keterangan = 'Duri Bengkalis' WHERE id_induk = '04-04-BZ';
UPDATE m_jemaat_induk SET nama_induk = 'EFFATA', keterangan = 'Pasaman' WHERE id_induk = '04-05-ET';
UPDATE m_jemaat_induk SET nama_induk = 'EFRATA', keterangan = 'Padang' WHERE id_induk = '04-06-EP';
UPDATE m_jemaat_induk SET nama_induk = 'EFRATA', keterangan = 'Kuantan Sengingi' WHERE id_induk = '04-07-EF';
UPDATE m_jemaat_induk SET nama_induk = 'EKKLESIA', keterangan = 'Dumai' WHERE id_induk = '04-08-ED';
UPDATE m_jemaat_induk SET nama_induk = 'GIBEON', keterangan = 'Rumbai Pekanbaru' WHERE id_induk = '04-09-GR';
UPDATE m_jemaat_induk SET nama_induk = 'KASIH ABADI', keterangan = 'Perawang Siak' WHERE id_induk = '04-11-KP';
UPDATE m_jemaat_induk SET nama_induk = 'MARTURIA', keterangan = 'Kuantan Sengingi' WHERE id_induk = '04-13-MK';
UPDATE m_jemaat_induk SET nama_induk = 'SILOAM', keterangan = 'Kota Baru Pekanbaru' WHERE id_induk = '04-14-SK';
UPDATE m_jemaat_induk SET nama_induk = 'SUMBER KASIH', keterangan = 'Indrapuri Kampar' WHERE id_induk = '04-15-SD';
UPDATE m_jemaat_induk SET nama_induk = 'RAFFLESIA', keterangan = 'Bengkulu' WHERE id_induk = '04-16-RB';
UPDATE m_jemaat_induk SET nama_induk = 'BAHTERA HAYAT', keterangan = 'Batam' WHERE id_induk = '03-01-BB';
UPDATE m_jemaat_induk SET nama_induk = 'BETHEL', keterangan = 'Tanjung Pinang' WHERE id_induk = '03-03-BT';
UPDATE m_jemaat_induk SET nama_induk = 'BUKIT KARMEL', keterangan = 'Dabo Singkep' WHERE id_induk = '03-04-BD';
UPDATE m_jemaat_induk SET nama_induk = 'BUKIT KASIH', keterangan = 'Ranai Natuna' WHERE id_induk = '03-10-BR';
UPDATE m_jemaat_induk SET nama_induk = 'EBENHAEZER', keterangan = 'Tanjung Batu Kundur' WHERE id_induk = '03-05-ET';
UPDATE m_jemaat_induk SET nama_induk = 'GETSEMANI', keterangan = 'Mengkait Anambas' WHERE id_induk = '03-12-Z';
UPDATE m_jemaat_induk SET nama_induk = 'HOSANA', keterangan = 'Tanjung Uban Bintan' WHERE id_induk = '03-06-HT';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Batam' WHERE id_induk = '03-07-IB';
UPDATE m_jemaat_induk SET nama_induk = 'SOLA GRATIA', keterangan = 'Bukit Layang, Tanjung Piayu Batam' WHERE id_induk = '03-13-Z';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Tarempa Anambas' WHERE id_induk = '03-08-IT';
UPDATE m_jemaat_induk SET nama_induk = 'ORA ET LABORA', keterangan = 'Tanjung Balai Karimun' WHERE id_induk = '05-09-OT';
UPDATE m_jemaat_induk SET nama_induk = 'ZEBULON', keterangan = 'Batam' WHERE id_induk = '03-11-ZS';
UPDATE m_jemaat_induk SET nama_induk = 'EZRA', keterangan = 'Tiangwangkang - Batam' WHERE id_induk = '03-14-EZ';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Palembang' WHERE id_induk = '05-04-IP';
UPDATE m_jemaat_induk SET nama_induk = 'EFRATA', keterangan = 'Bangun Jawa Lubuk Linggau' WHERE id_induk = '05-02-EL';
UPDATE m_jemaat_induk SET nama_induk = 'KARUNIA', keterangan = 'Muara Enim' WHERE id_induk = '05-05-KP';
UPDATE m_jemaat_induk SET nama_induk = 'PLAJU SUNGAI GERONG', keterangan = 'Sekojo Palembang' WHERE id_induk = '05-07-PS';
UPDATE m_jemaat_induk SET nama_induk = 'PNIEL', keterangan = 'Palembang' WHERE id_induk = '05-08-PP';
UPDATE m_jemaat_induk SET nama_induk = 'SANGKAKALA', keterangan = 'Ogan Komering Ilir' WHERE id_induk = '05-09-SB';
UPDATE m_jemaat_induk SET nama_induk = 'MARTURIA', keterangan = 'Jambi' WHERE id_induk = '05-06MJ';
UPDATE m_jemaat_induk SET nama_induk = 'BUKIT KASIH', keterangan = 'Sungai Penuh' WHERE id_induk = '04-03-BK';
UPDATE m_jemaat_induk SET nama_induk = 'ALFA OMEGA', keterangan = 'Sungai Bahar' WHERE id_induk = '05-01-AJ';
UPDATE m_jemaat_induk SET nama_induk = 'BUKIT DIAN KASIH', keterangan = 'Kayu Aro Kerinci' WHERE id_induk = '04-02-BD';
UPDATE m_jemaat_induk SET nama_induk = 'EKKLESIA', keterangan = 'Tanjung Jabung Barat' WHERE id_induk = '05-10-EJ';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Tempino' WHERE id_induk = '05-01-IJ';
UPDATE m_jemaat_induk SET nama_induk = 'MARANATHA', keterangan = 'Pangkal Pinang' WHERE id_induk = '02-06-MP';
UPDATE m_jemaat_induk SET nama_induk = 'BETHESDA', keterangan = 'Muntok' WHERE id_induk = '02-01-BM';
UPDATE m_jemaat_induk SET nama_induk = 'EFRATA', keterangan = 'Toboali' WHERE id_induk = '02-02-ET';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Belinyu' WHERE id_induk = '02-03-IB';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Tanjung Pandan' WHERE id_induk = '02-04-IT';
UPDATE m_jemaat_induk SET nama_induk = 'KARUNIA', keterangan = 'Manggar' WHERE id_induk = '02-05-KM';
UPDATE m_jemaat_induk SET nama_induk = 'ORA ET LABORA', keterangan = 'Sungai Liat' WHERE id_induk = '02-07-OS';
UPDATE m_jemaat_induk SET nama_induk = 'SION', keterangan = 'Koba' WHERE id_induk = '02-08-SK';
UPDATE m_jemaat_induk SET nama_induk = 'MARTURIA', keterangan = 'Bandar Lampung' WHERE id_induk = '06-05-MA';
UPDATE m_jemaat_induk SET nama_induk = 'BETH TEFILAH', keterangan = 'Pesawaran' WHERE id_induk = '06-01-BT';
UPDATE m_jemaat_induk SET nama_induk = 'EFFATHA', keterangan = 'Bandar Lampung' WHERE id_induk = '06-02-EF';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Pesawaran' WHERE id_induk = '06-03-IM';
UPDATE m_jemaat_induk SET nama_induk = 'KANAAN', keterangan = 'Lampung Tengah' WHERE id_induk = '06-11-KA';
UPDATE m_jemaat_induk SET nama_induk = 'MARANATHA', keterangan = 'Bandar Lampung' WHERE id_induk = '06-04-MR';
UPDATE m_jemaat_induk SET nama_induk = 'PANCARAN KASIH', keterangan = 'Tanggamus' WHERE id_induk = '06-06-PA';
UPDATE m_jemaat_induk SET nama_induk = 'PETRA', keterangan = 'Kota Bumi' WHERE id_induk = '06-07-PE';
UPDATE m_jemaat_induk SET nama_induk = 'SILO', keterangan = 'Panjang' WHERE id_induk = '06-08-SI';
UPDATE m_jemaat_induk SET nama_induk = 'TIBERIAS', keterangan = 'Lampung Tengah' WHERE id_induk = '06-09-TI';
UPDATE m_jemaat_induk SET nama_induk = 'ZEBAOTH', keterangan = 'Bangunrejo' WHERE id_induk = '06-10-ZE';
UPDATE m_jemaat_induk SET nama_induk = 'SYALOM PANCASILA', keterangan = 'Kotabumi Lampung Utara' WHERE id_induk = '06-12-SP';
UPDATE m_jemaat_induk SET nama_induk = 'MAKEDONIA', keterangan = 'Dipasena Lampung' WHERE id_induk = '06-13-MK';
UPDATE m_jemaat_induk SET nama_induk = 'FILADELFIA', keterangan = 'Bintaro' WHERE id_induk = '07-02-FI';
UPDATE m_jemaat_induk SET nama_induk = 'ABRAHAM', keterangan = 'Serang' WHERE id_induk = '07-12-AS';
UPDATE m_jemaat_induk SET nama_induk = 'BAHTERA IMAN', keterangan = 'Ciputat Tangerang' WHERE id_induk = '07-01-BI';
UPDATE m_jemaat_induk SET nama_induk = 'JURANG MANGU', keterangan = 'Tangerang Selatan' WHERE id_induk = '07-14-JM';
UPDATE m_jemaat_induk SET nama_induk = 'KARUNIA', keterangan = 'Ciputat Tangerang' WHERE id_induk = '07-03-KA';
UPDATE m_jemaat_induk SET nama_induk = 'KASIH KARUNIA', keterangan = 'Ciledug Tangerang' WHERE id_induk = '07-04-KK';
UPDATE m_jemaat_induk SET nama_induk = 'KASIH SETIA', keterangan = 'Tangerang' WHERE id_induk = '07-05-KS';
UPDATE m_jemaat_induk SET nama_induk = 'KINASIH', keterangan = 'Tangerang Selatan' WHERE id_induk = '07-06-KI';
UPDATE m_jemaat_induk SET nama_induk = 'OBOR BANTEN', keterangan = 'Tangerang Selatan' WHERE id_induk = '07-10-OB';
UPDATE m_jemaat_induk SET nama_induk = 'ORA ET LABORA', keterangan = 'Tangerang' WHERE id_induk = '07-11-OE';
UPDATE m_jemaat_induk SET nama_induk = 'PATMOS', keterangan = 'Tangerang' WHERE id_induk = '07-07-PA';
UPDATE m_jemaat_induk SET nama_induk = 'SAMARIA', keterangan = 'Tangerang' WHERE id_induk = '07-08-SA';
UPDATE m_jemaat_induk SET nama_induk = 'SINAR KASIH', keterangan = 'Kosambi Tangerang' WHERE id_induk = '07-13-SK';
UPDATE m_jemaat_induk SET nama_induk = 'YUDEA', keterangan = 'Tangerang' WHERE id_induk = '07-09-YU';
UPDATE m_jemaat_induk SET nama_induk = 'PAULUS', keterangan = 'Jakarta' WHERE id_induk = '10-10-PA';
UPDATE m_jemaat_induk SET nama_induk = 'ANUGERAH', keterangan = 'Jakarta' WHERE id_induk = '10-01-AN';
UPDATE m_jemaat_induk SET nama_induk = 'BETHESDA', keterangan = 'Jakarta' WHERE id_induk = '10-02-BA';
UPDATE m_jemaat_induk SET nama_induk = 'BETLEHEM', keterangan = 'Jakarta' WHERE id_induk = '10-03-BM';
UPDATE m_jemaat_induk SET nama_induk = 'BUKIT ZAITUN', keterangan = 'Jakarta' WHERE id_induk = '10-04-BZ';
UPDATE m_jemaat_induk SET nama_induk = 'EBENHAEZER', keterangan = 'Jakarta' WHERE id_induk = '10-05-EH';
UPDATE m_jemaat_induk SET nama_induk = 'GIDEON', keterangan = 'Jakarta' WHERE id_induk = '10-06-GI';
UPDATE m_jemaat_induk SET nama_induk = 'HOSIANA', keterangan = 'Jakarta' WHERE id_induk = '10-07-HO';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Jakarta' WHERE id_induk = '10-08-IM';
UPDATE m_jemaat_induk SET nama_induk = 'MARANATHA', keterangan = 'Jakarta' WHERE id_induk = '10-09-MA';
UPDATE m_jemaat_induk SET nama_induk = 'PETRUS', keterangan = 'Jakarta' WHERE id_induk = '10-11-PE';
UPDATE m_jemaat_induk SET nama_induk = 'PNIEL', keterangan = 'Jakarta' WHERE id_induk = '10-12-PN';
UPDATE m_jemaat_induk SET nama_induk = 'PETRA', keterangan = 'Jakarta' WHERE id_induk = '11-05-PE';
UPDATE m_jemaat_induk SET nama_induk = 'EIRENE', keterangan = 'Jakarta' WHERE id_induk = '11-01-EI';
UPDATE m_jemaat_induk SET nama_induk = 'GETSEMANI', keterangan = 'Jakarta' WHERE id_induk = '11-02-GE';
UPDATE m_jemaat_induk SET nama_induk = 'KELAPA GADING', keterangan = 'Jakarta' WHERE id_induk = '11-03-KE';
UPDATE m_jemaat_induk SET nama_induk = 'MENABUR KASIH', keterangan = 'Jakarta' WHERE id_induk = '11-04-ME';
UPDATE m_jemaat_induk SET nama_induk = 'TUGU', keterangan = 'Jakarta' WHERE id_induk = '11-06-TU';
UPDATE m_jemaat_induk SET nama_induk = 'BULAK TURI', keterangan = 'Marunda' WHERE id_induk = '11-07-BT';
UPDATE m_jemaat_induk SET nama_induk = 'SANGKAKALA', keterangan = 'Jakarta' WHERE id_induk = '08-01-SA';
UPDATE m_jemaat_induk SET nama_induk = 'SHALOM', keterangan = 'Jakarta' WHERE id_induk = '08-02-SH';
UPDATE m_jemaat_induk SET nama_induk = 'SION', keterangan = 'Jakarta' WHERE id_induk = '08-05-SN';
UPDATE m_jemaat_induk SET nama_induk = 'SILO', keterangan = 'Jakarta' WHERE id_induk = '08-03-SI';
UPDATE m_jemaat_induk SET nama_induk = 'SILOAM', keterangan = 'Jakarta' WHERE id_induk = '08-04-SM';
UPDATE m_jemaat_induk SET nama_induk = 'YAHYA', keterangan = 'Jakarta' WHERE id_induk = '08-06-YA';
UPDATE m_jemaat_induk SET nama_induk = 'PENABUR', keterangan = 'Jakarta' WHERE id_induk = '12-12-PR';
UPDATE m_jemaat_induk SET nama_induk = 'AGAPE', keterangan = 'Jakarta' WHERE id_induk = '12-01-AG';
UPDATE m_jemaat_induk SET nama_induk = 'BETHANIA', keterangan = 'Jakarta' WHERE id_induk = '12-02-BE';
UPDATE m_jemaat_induk SET nama_induk = 'CAWANG BARU', keterangan = 'Jakarta' WHERE id_induk = '12-03-CA';
UPDATE m_jemaat_induk SET nama_induk = 'HOREB', keterangan = 'Jakarta' WHERE id_induk = '12-04-HO';
UPDATE m_jemaat_induk SET nama_induk = 'KHARIS', keterangan = 'Jakarta' WHERE id_induk = '12-05-KH';
UPDATE m_jemaat_induk SET nama_induk = 'KOINONIA', keterangan = 'Jakarta' WHERE id_induk = '12-06-KO';
UPDATE m_jemaat_induk SET nama_induk = 'MARTIN LUTHER', keterangan = 'Jakarta' WHERE id_induk = '12-07-ML';
UPDATE m_jemaat_induk SET nama_induk = 'MARTURIA', keterangan = 'Jakarta' WHERE id_induk = '12-08-MA';
UPDATE m_jemaat_induk SET nama_induk = 'MENARA IMAN', keterangan = 'Jakarta' WHERE id_induk = '12-09-ME';
UPDATE m_jemaat_induk SET nama_induk = 'NAZARETH', keterangan = 'Jakarta' WHERE id_induk = '12-10-NA';
UPDATE m_jemaat_induk SET nama_induk = 'PELITA', keterangan = 'Jakarta' WHERE id_induk = '12-11-PE';
UPDATE m_jemaat_induk SET nama_induk = 'SURYA KASIH', keterangan = 'Jakarta' WHERE id_induk = '12-13-SU';
UPDATE m_jemaat_induk SET nama_induk = 'TAMAN HARAPAN', keterangan = 'Jakarta' WHERE id_induk = '12-14-TA';
UPDATE m_jemaat_induk SET nama_induk = 'TORSINA', keterangan = 'Jakarta' WHERE id_induk = '12-15-TO';
UPDATE m_jemaat_induk SET nama_induk = 'EFFATHA', keterangan = 'Jakarta' WHERE id_induk = '09-02-EF';
UPDATE m_jemaat_induk SET nama_induk = 'BUKIT MORIA', keterangan = 'Jakarta' WHERE id_induk = '09-01-BM';
UPDATE m_jemaat_induk SET nama_induk = 'EKKLESIA', keterangan = 'Jakarta' WHERE id_induk = '09-03-EK';
UPDATE m_jemaat_induk SET nama_induk = 'GIBEON', keterangan = 'Jakarta' WHERE id_induk = '09-04-GI';
UPDATE m_jemaat_induk SET nama_induk = 'KHARISMA', keterangan = 'Jakarta' WHERE id_induk = '09-05-KH';
UPDATE m_jemaat_induk SET nama_induk = 'MARKUS', keterangan = 'Jakarta' WHERE id_induk = '09-06-MA';
UPDATE m_jemaat_induk SET nama_induk = 'PASAR MINGGU', keterangan = 'Jakarta' WHERE id_induk = '09-07-PA';
UPDATE m_jemaat_induk SET nama_induk = 'SEJAHTERA', keterangan = 'Jakarta' WHERE id_induk = '09-08-SE';
UPDATE m_jemaat_induk SET nama_induk = 'SETIABUDI', keterangan = 'Jakarta' WHERE id_induk = '09-09-SI';
UPDATE m_jemaat_induk SET nama_induk = 'SUMBER KASIH', keterangan = 'Jakarta' WHERE id_induk = '09-10-SK';
UPDATE m_jemaat_induk SET nama_induk = 'JATIPON', keterangan = 'Bekasi' WHERE id_induk = '13-11-JA';
UPDATE m_jemaat_induk SET nama_induk = 'ANUGERAH', keterangan = 'Bekasi' WHERE id_induk = '13-01-AN';
UPDATE m_jemaat_induk SET nama_induk = 'BAHTERA KASIH', keterangan = 'Bekasi' WHERE id_induk = '13-02-BA';
UPDATE m_jemaat_induk SET nama_induk = 'DIAN KASIH', keterangan = 'Bekasi' WHERE id_induk = '13-03-DI';
UPDATE m_jemaat_induk SET nama_induk = 'GALILEA', keterangan = 'Bekasi' WHERE id_induk = '13-04-GA';
UPDATE m_jemaat_induk SET nama_induk = 'GLORIA', keterangan = 'Bekasi' WHERE id_induk = '13-05-GL';
UPDATE m_jemaat_induk SET nama_induk = 'GRATIA', keterangan = 'Bekasi' WHERE id_induk = '13-06-GR';
UPDATE m_jemaat_induk SET nama_induk = 'HARAPAN BARU', keterangan = 'Bekasi' WHERE id_induk = '13-07-HB';
UPDATE m_jemaat_induk SET nama_induk = 'HARAPAN INDAH', keterangan = 'Bekasi' WHERE id_induk = '13-08-HI';
UPDATE m_jemaat_induk SET nama_induk = 'HARAPAN KASIH', keterangan = 'Bekasi' WHERE id_induk = '13-09-HK';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Bekasi' WHERE id_induk = '13-10-IM';
UPDATE m_jemaat_induk SET nama_induk = 'MENARA KASIH', keterangan = 'Bekasi' WHERE id_induk = '13-12-MK';
UPDATE m_jemaat_induk SET nama_induk = 'PILAR ASIH', keterangan = 'Bekasi' WHERE id_induk = '13-14-PA';
UPDATE m_jemaat_induk SET nama_induk = 'PONDOK UNGU', keterangan = 'Bekasi' WHERE id_induk = '13-13-PU';
UPDATE m_jemaat_induk SET nama_induk = 'KARANG SATRIA', keterangan = 'Tambun Utara - Bekasi' WHERE id_induk = '13-14-KS';
UPDATE m_jemaat_induk SET nama_induk = 'SEJAHTERA', keterangan = 'Bandung' WHERE id_induk = '14-08-SB';
UPDATE m_jemaat_induk SET nama_induk = 'BETHEL', keterangan = 'Bandung' WHERE id_induk = '14-01-BB';
UPDATE m_jemaat_induk SET nama_induk = 'EFATA', keterangan = 'Batujajar Bandung Barat' WHERE id_induk = '14-02-EF';
UPDATE m_jemaat_induk SET nama_induk = 'GETSEMANI', keterangan = 'Cirebon' WHERE id_induk = '14-03-GC';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Cimahi' WHERE id_induk = '14-04-IC';
UPDATE m_jemaat_induk SET nama_induk = 'MARANATHA', keterangan = 'Bandung' WHERE id_induk = '14-05-MB';
UPDATE m_jemaat_induk SET nama_induk = 'MARANATHA', keterangan = 'Subang' WHERE id_induk = '14-06-MS';
UPDATE m_jemaat_induk SET nama_induk = 'PNIEL YUDHA WIYOGRAHA', keterangan = 'Dayeuhkolot Bandung' WHERE id_induk = '14-07-PB';
UPDATE m_jemaat_induk SET nama_induk = 'SILIH ASIH', keterangan = 'Bandung' WHERE id_induk = '14-09-SA';
UPDATE m_jemaat_induk SET nama_induk = 'SYALOOM', keterangan = 'Cikampek Karawang' WHERE id_induk = '14-10-SC';
UPDATE m_jemaat_induk SET nama_induk = 'WISMA ASIH', keterangan = 'Lembang Bandung Barat' WHERE id_induk = '14-11-WL';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Depok' WHERE id_induk = '15-05-ID';
UPDATE m_jemaat_induk SET nama_induk = 'BOJONG GEDE', keterangan = 'Bogor' WHERE id_induk = '15-20-BG';
UPDATE m_jemaat_induk SET nama_induk = 'BUKIT SENTUL', keterangan = 'Bogor' WHERE id_induk = '15-21-BS';
UPDATE m_jemaat_induk SET nama_induk = 'CIMANGGIS', keterangan = 'Depok' WHERE id_induk = '15-01-CD';
UPDATE m_jemaat_induk SET nama_induk = 'CINERE', keterangan = 'Depok' WHERE id_induk = '15-19-CD';
UPDATE m_jemaat_induk SET nama_induk = 'CIPEUCANG', keterangan = 'Jonggol Bogor' WHERE id_induk = '15-22-CP';
UPDATE m_jemaat_induk SET nama_induk = 'DAMAI SEJAHTERA', keterangan = 'Cileungsi Bogor' WHERE id_induk = '15-02-DS';
UPDATE m_jemaat_induk SET nama_induk = 'GALILEA', keterangan = 'Pelabuhan Ratu Sukabumi' WHERE id_induk = '15-03-GP';
UPDATE m_jemaat_induk SET nama_induk = 'GIDEON', keterangan = 'Kelapa Dua Cimanggis' WHERE id_induk = '15-04-GK';
UPDATE m_jemaat_induk SET nama_induk = 'KARTIKA SEJAHTERA', keterangan = 'Bogor' WHERE id_induk = '15-18-KS';
UPDATE m_jemaat_induk SET nama_induk = 'KORNELIUS', keterangan = 'Lido Bogor' WHERE id_induk = '15-06-KL';
UPDATE m_jemaat_induk SET nama_induk = 'NEHEMIA', keterangan = 'Cibogo Bogor' WHERE id_induk = '15-07-NC';
UPDATE m_jemaat_induk SET nama_induk = 'PANCARAN KASIH', keterangan = 'Depok' WHERE id_induk = '15-08-PK';
UPDATE m_jemaat_induk SET nama_induk = 'PANCORAN RAHMAT', keterangan = 'Depok' WHERE id_induk = '15-09-PD';
UPDATE m_jemaat_induk SET nama_induk = 'PELITA HIDUP', keterangan = 'Depok' WHERE id_induk = '15-10-PH';
UPDATE m_jemaat_induk SET nama_induk = 'PENGHARAPAN', keterangan = 'Cibinong Bogor' WHERE id_induk = '15-11-PC';
UPDATE m_jemaat_induk SET nama_induk = 'PETRA', keterangan = 'Ciluar Bogor' WHERE id_induk = '15-12-PB';
UPDATE m_jemaat_induk SET nama_induk = 'SAWANGAN', keterangan = 'Depok' WHERE id_induk = '15-13-SA';
UPDATE m_jemaat_induk SET nama_induk = 'SHALOM', keterangan = 'Beji Depok' WHERE id_induk = '15-15-SD';
UPDATE m_jemaat_induk SET nama_induk = 'SOLA GRATIA', keterangan = 'Semplak Bogor' WHERE id_induk = '15-14-SS';
UPDATE m_jemaat_induk SET nama_induk = 'TRINITAS', keterangan = 'Kota Wisata Cibubur' WHERE id_induk = '15-17-TK';
UPDATE m_jemaat_induk SET nama_induk = 'ZEBAOTH', keterangan = 'Bogor' WHERE id_induk = '15-16-ZB';
UPDATE m_jemaat_induk SET nama_induk = 'CISEENG', keterangan = 'Bogor' WHERE id_induk = '15-22-CS';
UPDATE m_jemaat_induk SET nama_induk = 'PURA TAJURHALANG', keterangan = 'Tajurhalang - Bogor' WHERE id_induk = '15-23-PT';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Semarang' WHERE id_induk = '16-06-IS';
UPDATE m_jemaat_induk SET nama_induk = 'AMBARAWA TAMBAKREJO KEBONDOWO', keterangan = 'Ambarawa' WHERE id_induk = '16-01-AS';
UPDATE m_jemaat_induk SET nama_induk = 'AYALON', keterangan = 'Tegal' WHERE id_induk = '16-02-AY';
UPDATE m_jemaat_induk SET nama_induk = 'BETHEL', keterangan = 'Magelang' WHERE id_induk = '16-07-MA';
UPDATE m_jemaat_induk SET nama_induk = 'CUPUWATU', keterangan = 'Sleman' WHERE id_induk = '16-15-CP';
UPDATE m_jemaat_induk SET nama_induk = 'EFFATHA', keterangan = 'Semarang' WHERE id_induk = '16-03-ES';
UPDATE m_jemaat_induk SET nama_induk = 'FILADELFIA', keterangan = 'Semarang' WHERE id_induk = '16-04-FS';
UPDATE m_jemaat_induk SET nama_induk = 'GALILEA', keterangan = 'Cilacap' WHERE id_induk = '16-05-GC';
UPDATE m_jemaat_induk SET nama_induk = 'GRIYA MULYA', keterangan = 'Purworejo' WHERE id_induk = '16-11-PU';
UPDATE m_jemaat_induk SET nama_induk = 'MARGA MULYA', keterangan = 'Yogyakarta' WHERE id_induk = '16-08-MY';
UPDATE m_jemaat_induk SET nama_induk = 'PENABUR', keterangan = 'Solo' WHERE id_induk = '16-10-PS';
UPDATE m_jemaat_induk SET nama_induk = 'SION', keterangan = 'Semarang' WHERE id_induk = '16-12-SS';
UPDATE m_jemaat_induk SET nama_induk = 'SOLO UTARA', keterangan = 'Solo' WHERE id_induk = '16-13-SU';
UPDATE m_jemaat_induk SET nama_induk = 'TAMAN SARI', keterangan = 'Salatiga' WHERE id_induk = '16-14-TS';
UPDATE m_jemaat_induk SET nama_induk = 'BETHLEHEM', keterangan = 'Gebyog, Purwoharjo - Comal' WHERE id_induk = '16-16-BT';
UPDATE m_jemaat_induk SET nama_induk = 'MARANATHA', keterangan = 'Surabaya' WHERE id_induk = '17-33-MS';
UPDATE m_jemaat_induk SET nama_induk = 'AIR HIDUP', keterangan = 'Kamal Madura' WHERE id_induk = '17-01-AK';
UPDATE m_jemaat_induk SET nama_induk = 'AIR KEHIDUPAN', keterangan = 'Blitar' WHERE id_induk = '17-02-AB';
UPDATE m_jemaat_induk SET nama_induk = 'BAHTERA HAYAT', keterangan = 'Surabaya' WHERE id_induk = '17-03-BH';
UPDATE m_jemaat_induk SET nama_induk = 'BAHTERA KASIH', keterangan = 'Gresik' WHERE id_induk = '17-04-BG';
UPDATE m_jemaat_induk SET nama_induk = 'BENOWO', keterangan = 'Surabaya' WHERE id_induk = '17-48-BS';
UPDATE m_jemaat_induk SET nama_induk = 'BETHESDA', keterangan = 'Sidoarjo' WHERE id_induk = '17-05-BE';
UPDATE m_jemaat_induk SET nama_induk = 'BHASKARA', keterangan = 'Surabaya' WHERE id_induk = '17-06-BH';
UPDATE m_jemaat_induk SET nama_induk = 'BUKIT HARAPAN', keterangan = 'Surabaya' WHERE id_induk = '17-07-BU';
UPDATE m_jemaat_induk SET nama_induk = 'BUKIT KASIH', keterangan = 'Surabaya' WHERE id_induk = '17-08-BK';
UPDATE m_jemaat_induk SET nama_induk = 'BUKIT SION', keterangan = 'Surabaya' WHERE id_induk = '17-09-BS';
UPDATE m_jemaat_induk SET nama_induk = 'BUKIT ZAITUN', keterangan = 'Surabaya' WHERE id_induk = '17-10-BZ';
UPDATE m_jemaat_induk SET nama_induk = 'CAHAYA ANUGERAH', keterangan = 'Surabaya' WHERE id_induk = '17-11-CA';
UPDATE m_jemaat_induk SET nama_induk = 'CAHAYA KASIH', keterangan = 'Surabaya' WHERE id_induk = '17-12-CK';
UPDATE m_jemaat_induk SET nama_induk = 'EBENHAEZER', keterangan = 'Surabaya' WHERE id_induk = '17-14-ES';
UPDATE m_jemaat_induk SET nama_induk = 'EBENHAEZER', keterangan = 'Blitar' WHERE id_induk = '17-13-EB';
UPDATE m_jemaat_induk SET nama_induk = 'EFRATA', keterangan = 'Surabaya' WHERE id_induk = '17-16-EF';
UPDATE m_jemaat_induk SET nama_induk = 'EFFATHA', keterangan = 'Glenmore, Banyuwangi' WHERE id_induk = '17-15-EG';
UPDATE m_jemaat_induk SET nama_induk = 'GALILEA', keterangan = 'Surabaya' WHERE id_induk = '17-17-GS';
UPDATE m_jemaat_induk SET nama_induk = 'GAMALIEL', keterangan = 'Madiun' WHERE id_induk = '17-18-GM';
UPDATE m_jemaat_induk SET nama_induk = 'GENTA KASIH', keterangan = 'Surabaya' WHERE id_induk = '17-19-GK';
UPDATE m_jemaat_induk SET nama_induk = 'GETSEMANI', keterangan = 'Jember' WHERE id_induk = '17-20-GJ';
UPDATE m_jemaat_induk SET nama_induk = 'GETSEMANI', keterangan = 'Malang' WHERE id_induk = '17-21-GE';
UPDATE m_jemaat_induk SET nama_induk = 'HOSEA', keterangan = 'Surabaya' WHERE id_induk = '17-22-HS';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Surabaya' WHERE id_induk = '17-30-IS';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Banyuwangi' WHERE id_induk = '17-24-IL';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Bangil' WHERE id_induk = '17-23-IB';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Bondowoso' WHERE id_induk = '17-25-II';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Kediri' WHERE id_induk = '17-26-IK';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Malang' WHERE id_induk = '17-27-IM';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Mojokerto' WHERE id_induk = '17-28-IO';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Probolinggo' WHERE id_induk = '17-29-IP';
UPDATE m_jemaat_induk SET nama_induk = 'MARANATHA', keterangan = 'Bojonegoro' WHERE id_induk = '17-32-MB';
UPDATE m_jemaat_induk SET nama_induk = 'MAHKOTA HAYAT', keterangan = 'Pamekasan Madura' WHERE id_induk = '17-31-MH';
UPDATE m_jemaat_induk SET nama_induk = 'MARGO MULYO', keterangan = 'Batu Malang' WHERE id_induk = '17-34-MM';
UPDATE m_jemaat_induk SET nama_induk = 'NAZARETH', keterangan = 'Surabaya' WHERE id_induk = '17-35-NZ';
UPDATE m_jemaat_induk SET nama_induk = 'PANCARAN KASIH', keterangan = 'Sumenep Madura' WHERE id_induk = '17-36-PK';
UPDATE m_jemaat_induk SET nama_induk = 'PANCARAN KASIH', keterangan = 'Lumajang' WHERE id_induk = '17-37-PL';
UPDATE m_jemaat_induk SET nama_induk = 'PELANGI KASIH', keterangan = 'Lawang' WHERE id_induk = '17-38-PE';
UPDATE m_jemaat_induk SET nama_induk = 'PNIEL', keterangan = 'Surabaya' WHERE id_induk = '17-40-PS';
UPDATE m_jemaat_induk SET nama_induk = 'PNIEL', keterangan = 'Pasuruan' WHERE id_induk = '17-39-PP';
UPDATE m_jemaat_induk SET nama_induk = 'SEJAHERA', keterangan = 'Surabaya' WHERE id_induk = '17-42-SS';
UPDATE m_jemaat_induk SET nama_induk = 'SEJAHTERA', keterangan = 'Malang' WHERE id_induk = '17-41-SM';
UPDATE m_jemaat_induk SET nama_induk = 'SINAI', keterangan = 'Surabaya' WHERE id_induk = '17-44-SI';
UPDATE m_jemaat_induk SET nama_induk = 'SHALOM', keterangan = 'Sidoarjo' WHERE id_induk = '17-43-SH';
UPDATE m_jemaat_induk SET nama_induk = 'SURYA KASIH', keterangan = 'Situbondo' WHERE id_induk = '17-45-SK';
UPDATE m_jemaat_induk SET nama_induk = 'TIBERIAS', keterangan = 'Sidoarjo' WHERE id_induk = '17-46-TS';
UPDATE m_jemaat_induk SET nama_induk = 'TORSINA', keterangan = 'Surabaya' WHERE id_induk = '17-47-TD';
UPDATE m_jemaat_induk SET nama_induk = 'SOLAFIDE', keterangan = 'Porong - Jawa Timur' WHERE id_induk = '17-49-SL';
UPDATE m_jemaat_induk SET nama_induk = 'MARANATHA', keterangan = 'Denpasar' WHERE id_induk = '18-04-MD';
UPDATE m_jemaat_induk SET nama_induk = 'EBENHAEZER', keterangan = 'Gianyar' WHERE id_induk = '18-01-EG';
UPDATE m_jemaat_induk SET nama_induk = 'EKKLESIA', keterangan = 'Tuban Kuta' WHERE id_induk = '18-02-EK';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL WR SUPRATMAN', keterangan = 'Mataram Lombok' WHERE id_induk = '18-07-WS';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL BUNG KARNO', keterangan = 'Mararam Lombok' WHERE id_induk = '18-03-IM';
UPDATE m_jemaat_induk SET nama_induk = 'JEMBRANA', keterangan = 'Negara Jembrana' WHERE id_induk = '18-09-JN';
UPDATE m_jemaat_induk SET nama_induk = 'KASIH KARUNIA', keterangan = 'Denpasar' WHERE id_induk = '18-08-KK';
UPDATE m_jemaat_induk SET nama_induk = 'PNIEL', keterangan = 'Singaraja Buleleng' WHERE id_induk = '18-05-PS';
UPDATE m_jemaat_induk SET nama_induk = 'SYALOM', keterangan = 'Denpasar' WHERE id_induk = '18-06-SD';
UPDATE m_jemaat_induk SET nama_induk = 'GETSEMANI', keterangan = 'Jimbaran' WHERE id_induk = '18-10-GS';
UPDATE m_jemaat_induk SET nama_induk = 'SILOAM', keterangan = 'Pontianak' WHERE id_induk = '20-13-SP';
UPDATE m_jemaat_induk SET nama_induk = 'ANUGERAH', keterangan = 'Beduai - Sanggau' WHERE id_induk = '20-01-AB';
UPDATE m_jemaat_induk SET nama_induk = 'BETHESDA', keterangan = 'Marau' WHERE id_induk = '20-02-BM';
UPDATE m_jemaat_induk SET nama_induk = 'MARANATHA', keterangan = 'Penyiuran' WHERE id_induk = '20-21-S';
UPDATE m_jemaat_induk SET nama_induk = 'BETLEHEM', keterangan = 'Sei Ambawang Kubu Raya' WHERE id_induk = '20-03-BP';
UPDATE m_jemaat_induk SET nama_induk = 'BUKIT AGAPE', keterangan = 'Entikong' WHERE id_induk = '20-15-BA';
UPDATE m_jemaat_induk SET nama_induk = 'EBENHAEZER', keterangan = 'Kembayan' WHERE id_induk = '20-20-S';
UPDATE m_jemaat_induk SET nama_induk = 'EBENHAEZER', keterangan = 'Ketapang - 1986' WHERE id_induk = '20-04-EK';
UPDATE m_jemaat_induk SET nama_induk = 'EKKLESIA', keterangan = 'GPIB Jemaat "Ekklesia" Air Upas' WHERE id_induk = '20-16-EA';
UPDATE m_jemaat_induk SET nama_induk = 'ICHTUS', keterangan = NULL WHERE id_induk = '20-05-IT';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'SINGKAWANG' WHERE id_induk = '20-19-S';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Singkawang' WHERE id_induk = '20-06-IS';
UPDATE m_jemaat_induk SET nama_induk = 'MAMURAJA', keterangan = 'Sungai Raya' WHERE id_induk = '20-18-MS';
UPDATE m_jemaat_induk SET nama_induk = 'MARANATHA', keterangan = 'Sanggau' WHERE id_induk = '20-07-MS';
UPDATE m_jemaat_induk SET nama_induk = 'MARGAHAYU', keterangan = 'Rasau Jaya' WHERE id_induk = '20-17-MR';
UPDATE m_jemaat_induk SET nama_induk = 'MENARA IMAN', keterangan = 'Sekayam Sanggau' WHERE id_induk = '20-08-MI';
UPDATE m_jemaat_induk SET nama_induk = 'ORA ET LABORA', keterangan = 'Semunte, Sanggau' WHERE id_induk = '20-09-OS';
UPDATE m_jemaat_induk SET nama_induk = 'PANAMPA', keterangan = 'Kepayang' WHERE id_induk = '20-14-PK';
UPDATE m_jemaat_induk SET nama_induk = 'PANITAH', keterangan = 'Anjungan' WHERE id_induk = '20-10-PA';
UPDATE m_jemaat_induk SET nama_induk = 'SEJAHTERA', keterangan = 'Jl. Raya Sosok II No.1, Sosok, Kec. Tayan Hulu, Kabupaten Sanggau, Kalimantan Barat 78562' WHERE id_induk = '20-11-SS';
UPDATE m_jemaat_induk SET nama_induk = 'SYALOOM', keterangan = 'Sungai Kajang' WHERE id_induk = '20-12-SK';
UPDATE m_jemaat_induk SET nama_induk = 'BUKIT ZAITUN', keterangan = 'Air Durian' WHERE id_induk = '20-22-BZ';
UPDATE m_jemaat_induk SET nama_induk = 'BALAI BATUAH', keterangan = 'Putaran' WHERE id_induk = '20-23-BB';
UPDATE m_jemaat_induk SET nama_induk = 'PAMA JUBATA', keterangan = 'Tapah, Pancaroba - Sungai Ambawang' WHERE id_induk = '20-24-PJ';
UPDATE m_jemaat_induk SET nama_induk = 'MARANATHA', keterangan = 'Banjarmasin' WHERE id_induk = '21-05-MB';
UPDATE m_jemaat_induk SET nama_induk = 'EBENHAEZER', keterangan = 'Palangkaraya' WHERE id_induk = '21-01-EH';
UPDATE m_jemaat_induk SET nama_induk = 'EFFATHA', keterangan = 'Guntung Payung Banjar Baru' WHERE id_induk = '21-02-RP';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Kotabaru' WHERE id_induk = '21-04-IK';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Landasan Ulin, Banjarbaru' WHERE id_induk = '21-03-IB';
UPDATE m_jemaat_induk SET nama_induk = 'SOLA GRATIA', keterangan = 'Batu Licin Tanah Bumbu' WHERE id_induk = '21-06-SB';
UPDATE m_jemaat_induk SET nama_induk = 'MARANATHA', keterangan = 'Balikpapan' WHERE id_induk = '22-08-MB';
UPDATE m_jemaat_induk SET nama_induk = 'BUKIT BENUAS', keterangan = 'Sepinggan Balikpapan' WHERE id_induk = '22-02-BB';
UPDATE m_jemaat_induk SET nama_induk = 'BUKIT SION', keterangan = 'Balikpapan' WHERE id_induk = '22-01-BD';
UPDATE m_jemaat_induk SET nama_induk = 'EBENHAEZER', keterangan = 'Paser' WHERE id_induk = '22-03-ET';
UPDATE m_jemaat_induk SET nama_induk = 'EFFATHA', keterangan = 'GPIB Effatha Batu Kajang, Jl. Boyan Belanda Gang Petra RT 027/000, Desa Batu Kajang, Kec. Batu Sopang, Kab. Paser, Kalimantan Timur' WHERE id_induk = '22-04-EB';
UPDATE m_jemaat_induk SET nama_induk = 'GETSEMANI', keterangan = 'Balikpapan' WHERE id_induk = '22-05-GB';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Balikpapan' WHERE id_induk = '22-06-IB';
UPDATE m_jemaat_induk SET nama_induk = 'KANAAN', keterangan = 'Kenangan' WHERE id_induk = '22-07-KK';
UPDATE m_jemaat_induk SET nama_induk = 'PNIEL', keterangan = 'Balikpapan' WHERE id_induk = '22-09-PB';
UPDATE m_jemaat_induk SET nama_induk = 'SILOAM', keterangan = 'Krayan Paser' WHERE id_induk = '22-10-SK';
UPDATE m_jemaat_induk SET nama_induk = 'SION', keterangan = 'Samuntai Paser' WHERE id_induk = '22-12-SS';
UPDATE m_jemaat_induk SET nama_induk = 'SYALOOM', keterangan = NULL WHERE id_induk = '22-11-SB';
UPDATE m_jemaat_induk SET nama_induk = 'ALAT ALA NGOSANG', keterangan = 'Long Gelang - Paser' WHERE id_induk = '22-13-AA';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Samarinda' WHERE id_induk = '23-06-IS';
UPDATE m_jemaat_induk SET nama_induk = 'ANUGERAH', keterangan = 'Kutai Kartanegara' WHERE id_induk = '23-01-AH';
UPDATE m_jemaat_induk SET nama_induk = 'EBENHAEZER', keterangan = 'Samarinda' WHERE id_induk = '23-02-ES';
UPDATE m_jemaat_induk SET nama_induk = 'EFATA', keterangan = 'Tenggarong' WHERE id_induk = '23-03-ET';
UPDATE m_jemaat_induk SET nama_induk = 'GLORIA', keterangan = 'Tenggarong' WHERE id_induk = '23-04-GT';
UPDATE m_jemaat_induk SET nama_induk = 'HEBRON', keterangan = 'Samarinda Seberang' WHERE id_induk = '23-14-HS';
UPDATE m_jemaat_induk SET nama_induk = 'HOSANA', keterangan = 'Loa Ulung' WHERE id_induk = '23-15-HS';
UPDATE m_jemaat_induk SET nama_induk = 'MARANATHA', keterangan = 'Sungai Sanga' WHERE id_induk = '23-07-MS';
UPDATE m_jemaat_induk SET nama_induk = 'MARTURIA', keterangan = 'Loa Janan' WHERE id_induk = '23-13-ML';
UPDATE m_jemaat_induk SET nama_induk = 'PANCARAN KASIH', keterangan = 'Bengalon' WHERE id_induk = '23-16-PK';
UPDATE m_jemaat_induk SET nama_induk = 'PELITA KASIH', keterangan = 'Sangatta' WHERE id_induk = '23-08-PS';
UPDATE m_jemaat_induk SET nama_induk = 'SION', keterangan = 'Jahab Kutai Kertanegara' WHERE id_induk = '23-09-SJ';
UPDATE m_jemaat_induk SET nama_induk = 'SOLA GRACIA', keterangan = 'Marang Kayu' WHERE id_induk = '23-12-SG';
UPDATE m_jemaat_induk SET nama_induk = 'SOLAFIDE', keterangan = 'Muara Badak' WHERE id_induk = '23-10-SM';
UPDATE m_jemaat_induk SET nama_induk = 'SUMBER KASIH', keterangan = 'Bontang' WHERE id_induk = '23-11-SK';
UPDATE m_jemaat_induk SET nama_induk = 'TELUK DALAM', keterangan = 'Tenggarong Seberang' WHERE id_induk = '23-17-TD';
UPDATE m_jemaat_induk SET nama_induk = 'MARANATHA', keterangan = 'Tanjung Selor' WHERE id_induk = '24-05-MT';
UPDATE m_jemaat_induk SET nama_induk = 'ANUGERAH', keterangan = 'Tarakan' WHERE id_induk = '24-08-AJ';
UPDATE m_jemaat_induk SET nama_induk = 'BETHEL', keterangan = 'Teras Nawang' WHERE id_induk = '24-09-BT';
UPDATE m_jemaat_induk SET nama_induk = 'BETLEHEM', keterangan = 'Malinau' WHERE id_induk = '24-01-BM';
UPDATE m_jemaat_induk SET nama_induk = 'EFFATHA', keterangan = 'Pulau Bunyu' WHERE id_induk = '24-02-EB';
UPDATE m_jemaat_induk SET nama_induk = 'HOSIANA', keterangan = 'Berau' WHERE id_induk = '24-03-HB';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Tarakan' WHERE id_induk = '24-04-IT';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Apau Kayan' WHERE id_induk = '23-05-IA';
UPDATE m_jemaat_induk SET nama_induk = 'SION', keterangan = 'Nunukan' WHERE id_induk = '24-06-SN';
UPDATE m_jemaat_induk SET nama_induk = 'U''UNG PENGELESAU', keterangan = 'Pujungan' WHERE id_induk = '24-07-UP';
UPDATE m_jemaat_induk SET nama_induk = 'SION', keterangan = 'Tembudan' WHERE id_induk = '24-08-SI';
UPDATE m_jemaat_induk SET nama_induk = 'FETEPAY', keterangan = 'Tarakan' WHERE id_induk = '24-09-FT';
UPDATE m_jemaat_induk SET nama_induk = 'SUNGAI SEGAH', keterangan = 'Tepian Buah' WHERE id_induk = '24-10-SS';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Makassar' WHERE id_induk = '19-02-IM';
UPDATE m_jemaat_induk SET nama_induk = 'BAHTERA KASIH', keterangan = 'Makassar' WHERE id_induk = '19-01-BK';
UPDATE m_jemaat_induk SET nama_induk = 'BETHANIA', keterangan = 'Makassar' WHERE id_induk = '19-03-BM';
UPDATE m_jemaat_induk SET nama_induk = 'BETHEL', keterangan = 'Raha Muna' WHERE id_induk = '19-04-BR';
UPDATE m_jemaat_induk SET nama_induk = 'BUKIT ZAITUN', keterangan = 'Makassar' WHERE id_induk = '19-05-BZ';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Baubau' WHERE id_induk = '19-06-IB';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Majene' WHERE id_induk = '19-07-IM';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Parepare' WHERE id_induk = '19-08-IP';
UPDATE m_jemaat_induk SET nama_induk = 'IMMANUEL', keterangan = 'Watampone Bone' WHERE id_induk = '19-10-IW';
UPDATE m_jemaat_induk SET nama_induk = 'KANA TOJENG', keterangan = 'Sungguminasa Gowa' WHERE id_induk = '19-11-KT';
UPDATE m_jemaat_induk SET nama_induk = 'MANGNGAMASEANG', keterangan = 'Makassar' WHERE id_induk = '19-12-MM';
UPDATE m_jemaat_induk SET nama_induk = 'PAMMASE', keterangan = 'Makassar' WHERE id_induk = '19-13-PM';
UPDATE m_jemaat_induk SET nama_induk = 'PELITA', keterangan = 'Baras Pasangkayu' WHERE id_induk = '19-14-PB';
UPDATE m_jemaat_induk SET nama_induk = 'SINAR KASIH', keterangan = 'Baras Pasangkayu' WHERE id_induk = '19-15-SB';
UPDATE m_jemaat_induk SET nama_induk = 'SOLA FIDE', keterangan = 'Sarudu Pasangkayu' WHERE id_induk = '19-16-SS';
UPDATE m_jemaat_induk SET nama_induk = 'SUMBER KASIH', keterangan = 'Kendari' WHERE id_induk = '19-17-SK';

-- 3. Update m_pos_pelkes (cleaned names & set kategori Bajem / Pos Pelkes)
UPDATE m_pos_pelkes SET nama_pos = 'Parittiga', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-13055';
UPDATE m_pos_pelkes SET nama_pos = 'Cupat', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-23592';
UPDATE m_pos_pelkes SET nama_pos = 'Pos pelkes Bethel binusan', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-88231';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Immanuel Bambangan', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-88016';
UPDATE m_pos_pelkes SET nama_pos = 'Alfa & Omega Nanga Tayap', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-55936';
UPDATE m_pos_pelkes SET nama_pos = NULL, kategori = 'Pos Pelkes' WHERE id_pos = 'POS-52126';
UPDATE m_pos_pelkes SET nama_pos = 'Exaudia Muara Bulian', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-57228';
UPDATE m_pos_pelkes SET nama_pos = 'PT. GAN', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-78047';
UPDATE m_pos_pelkes SET nama_pos = 'Kasih Karunia Kandis', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-94346';
UPDATE m_pos_pelkes SET nama_pos = 'Kasih Karunia Libo', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-56609';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Secanggang', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-23848';
UPDATE m_pos_pelkes SET nama_pos = 'Agape babulu', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-56943';
UPDATE m_pos_pelkes SET nama_pos = 'Ekklesia penajam', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-25763';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes "Eben Haezer" Tripariq Makmur, Long Hubung', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-81917';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes "Bukit Moria" Selesung', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-16368';
UPDATE m_pos_pelkes SET nama_pos = 'Bethesda Tonda', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-50712';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Teluk Kelapa', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-42271';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Tanjung Medan', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-34421';
UPDATE m_pos_pelkes SET nama_pos = 'Efrata', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-22291';
UPDATE m_pos_pelkes SET nama_pos = 'Maranatha', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-79937';
UPDATE m_pos_pelkes SET nama_pos = 'Paulus Wonosobo', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-37858';
UPDATE m_pos_pelkes SET nama_pos = 'Bethlehem Baturuguk', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-54277';
UPDATE m_pos_pelkes SET nama_pos = 'Pospelkes Immanuel Tj Medang', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-47744';
UPDATE m_pos_pelkes SET nama_pos = 'Pospelkes Maranatha Sei Pakning', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-81640';
UPDATE m_pos_pelkes SET nama_pos = 'Pospelkes Solafide Selat Panjang', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-54609';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Semoi Sepaku', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-75205';
UPDATE m_pos_pelkes SET nama_pos = 'Bajem Wonobakti', kategori = 'Bajem' WHERE id_pos = 'POS-16608';
UPDATE m_pos_pelkes SET nama_pos = 'Purwosari', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-56473';
UPDATE m_pos_pelkes SET nama_pos = 'Natar', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-60853';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Alfa-Omega Sarawak-Malaysia', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-67801';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Bubung Merege Punti Tapau', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-82867';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Remin Tempak Sontas', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-24806';
UPDATE m_pos_pelkes SET nama_pos = 'Efratha Kaliampu', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-58644';
UPDATE m_pos_pelkes SET nama_pos = 'Ekklesia Suka Damai', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-25545';
UPDATE m_pos_pelkes SET nama_pos = 'Maranatha Natai Panjang', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-92535';
UPDATE m_pos_pelkes SET nama_pos = 'Bajem Bukit Zaitun', kategori = 'Bajem' WHERE id_pos = 'POS-43938';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Kasih Karunia Bagan Manunggal', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-94852';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Sambi', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-17113';
UPDATE m_pos_pelkes SET nama_pos = 'PosPelkes Air Hidup Setogor', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-27157';
UPDATE m_pos_pelkes SET nama_pos = 'PosPelkes Roti Hidup Munyau', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-58999';
UPDATE m_pos_pelkes SET nama_pos = 'Bajem Sion Sei Rokan', kategori = 'Bajem' WHERE id_pos = 'POS-78262';
UPDATE m_pos_pelkes SET nama_pos = 'Jangkang', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-69672';
UPDATE m_pos_pelkes SET nama_pos = 'SUMBER KASIH TANJUNG AGUNG', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-39676';
UPDATE m_pos_pelkes SET nama_pos = 'EFRAT SAJAU', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-26959';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Maranatha', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-55766';
UPDATE m_pos_pelkes SET nama_pos = 'Beth Eden', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-93187';
UPDATE m_pos_pelkes SET nama_pos = 'Zebaoth', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-39582';
UPDATE m_pos_pelkes SET nama_pos = 'Bukit Zaitun', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-93631';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Anugerah Sempuat', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-79335';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Maranatha Karangan', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-43988';
UPDATE m_pos_pelkes SET nama_pos = 'Bajem Kembangsari', kategori = 'Bajem' WHERE id_pos = 'POS-15217';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pel Kalimangli', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-58201';
UPDATE m_pos_pelkes SET nama_pos = 'Pos PelKes Lembah Silo Gunung Seriang', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-29929';
UPDATE m_pos_pelkes SET nama_pos = 'Pos PelKes Tiberias Selimau', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-85526';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Lempake', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-70892';
UPDATE m_pos_pelkes SET nama_pos = 'Sola Fide Carik', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-17296';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes "Kanaan" Blambangan Umpu', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-92343';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes "Emaus" Gedung Harapan', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-33478';
UPDATE m_pos_pelkes SET nama_pos = '"KANAAN" Barong Tongkok', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-17861';
UPDATE m_pos_pelkes SET nama_pos = 'Kalam Hidup, Entubah', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-95078';
UPDATE m_pos_pelkes SET nama_pos = 'Bajem Getsemani', kategori = 'Bajem' WHERE id_pos = 'POS-36023';
UPDATE m_pos_pelkes SET nama_pos = 'Bajem Shalom', kategori = 'Bajem' WHERE id_pos = 'POS-71267';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Bukit Moria Tabalar', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-32914';
UPDATE m_pos_pelkes SET nama_pos = 'Bajem Immanuel Lipat Gunting', kategori = 'Bajem' WHERE id_pos = 'POS-65842';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Bukit Moria Kuala Asam', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-58666';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Syalom Batu Leman', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-10631';
UPDATE m_pos_pelkes SET nama_pos = NULL, kategori = 'Pos Pelkes' WHERE id_pos = 'POS-16012';
UPDATE m_pos_pelkes SET nama_pos = 'Pospelkes Immanuel sesulung', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-41565';
UPDATE m_pos_pelkes SET nama_pos = 'Gunung Sinai', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-58102';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Immanuel Kayungo Sari', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-18578';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Batu Tinggi Celengan', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-10552';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Kasih Karunia - Riam Kusik', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-50367';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkese Batu Tinggi, Celengan', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-44209';
UPDATE m_pos_pelkes SET nama_pos = 'Aras Tamiang Bakung', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-81077';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Anugerah Sanggau Ledo', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-48853';
UPDATE m_pos_pelkes SET nama_pos = 'pos Pelkes Sion Elok Asam', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-25425';
UPDATE m_pos_pelkes SET nama_pos = 'POS PELKES BUKIT SION SABUNG', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-25377';
UPDATE m_pos_pelkes SET nama_pos = 'Agape, Kempas Jaya', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-96495';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Effata Belilas', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-80533';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Pancaran Kasih DK3', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-30445';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Sumber Kasih DU', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-49169';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes "Bukit Sinai" Sanjan Emberas', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-42125';
UPDATE m_pos_pelkes SET nama_pos = 'kembiri', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-62666';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Maranatha Rantau Pulung', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-31031';
UPDATE m_pos_pelkes SET nama_pos = 'Bajem Immanuel Pengancing', kategori = 'Bajem' WHERE id_pos = 'POS-70716';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Tigris Batu Pindah', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-46102';
UPDATE m_pos_pelkes SET nama_pos = 'Pelita Iman Batang Belian', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-63796';
UPDATE m_pos_pelkes SET nama_pos = NULL, kategori = 'Pos Pelkes' WHERE id_pos = 'POS-77756';
UPDATE m_pos_pelkes SET nama_pos = NULL, kategori = 'Pos Pelkes' WHERE id_pos = 'POS-68350';
UPDATE m_pos_pelkes SET nama_pos = 'POS PELKES WAY HANDOP', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-81850';
UPDATE m_pos_pelkes SET nama_pos = 'Anugerah Selimatan Jaya', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-27137';
UPDATE m_pos_pelkes SET nama_pos = 'Ekklesia Singkup', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-59077';
UPDATE m_pos_pelkes SET nama_pos = 'Bajem "Maranatha" Batu Keling', kategori = 'Bajem' WHERE id_pos = 'POS-64442';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes "Arai Hidup" Perimping', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-94933';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes ELIM, Dusun Modah', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-63984';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Gembala Baik, Dusun Rantau', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-35232';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes "Bethesda" Palaran', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-31969';
UPDATE m_pos_pelkes SET nama_pos = 'Pospelkes Immanuel Batu Ampar', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-99872';
UPDATE m_pos_pelkes SET nama_pos = 'Bajem Maranatha Kombeng', kategori = 'Bajem' WHERE id_pos = 'POS-13298';
UPDATE m_pos_pelkes SET nama_pos = 'Pniel Seponti Jaya', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-23122';
UPDATE m_pos_pelkes SET nama_pos = '"Getsemani" Long Mesangat', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-40296';
UPDATE m_pos_pelkes SET nama_pos = 'Pu''un Udip', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-66516';
UPDATE m_pos_pelkes SET nama_pos = 'Haleluya', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-78010';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Bukit Sion Sungai Melayu Rayak', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-78468';
UPDATE m_pos_pelkes SET nama_pos = 'Simanduma', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-62648';
UPDATE m_pos_pelkes SET nama_pos = 'Tanjung Beringin', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-40402';
UPDATE m_pos_pelkes SET nama_pos = 'Gomit', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-26573';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Tonduhan', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-65205';
UPDATE m_pos_pelkes SET nama_pos = 'Arai Hidup Sepauhan', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-88508';
UPDATE m_pos_pelkes SET nama_pos = 'Tiberias Mahawa', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-38948';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Nehemia Pulau Kubung', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-58314';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Soli Deo PT. LAP', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-54069';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Talitakum Beringin', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-54989';
UPDATE m_pos_pelkes SET nama_pos = 'Bajem Anugerah Serengkah', kategori = 'Bajem' WHERE id_pos = 'POS-59271';
UPDATE m_pos_pelkes SET nama_pos = '"Timotius" Margorejo', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-93613';
UPDATE m_pos_pelkes SET nama_pos = '"Baithani" Papan Rejo', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-24519';
UPDATE m_pos_pelkes SET nama_pos = '"Imanuel" Propau', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-32475';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Pancaran Kasih Muara Kate', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-19929';
UPDATE m_pos_pelkes SET nama_pos = 'Pospelkes "Anugerah" Sekang', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-76733';
UPDATE m_pos_pelkes SET nama_pos = 'Pospelkes "Kanaan" Pejalin', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-42584';
UPDATE m_pos_pelkes SET nama_pos = 'GPIB Pos Pelkes Gideon Sebuduh', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-91941';
UPDATE m_pos_pelkes SET nama_pos = 'GPIB Pos Pelkes Penabur Ngoyok', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-18785';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Pancaran Kasih Naga Mas Estate', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-41348';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Pancaran Kasih Tapung Makmur', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-48869';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Maranatha PT. Cerenti Subur', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-38720';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Bukit Sion PT. KTBM', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-30508';
UPDATE m_pos_pelkes SET nama_pos = 'Bajem Agape Mersam', kategori = 'Bajem' WHERE id_pos = 'POS-13537';
UPDATE m_pos_pelkes SET nama_pos = 'Bakal Jemaat "Maranatha" Nawang Baru', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-79471';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Siloam Tadoan', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-56819';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes "Bethesda" Rantau Rasau', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-97404';
UPDATE m_pos_pelkes SET nama_pos = 'Bethel Lontar', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-83988';
UPDATE m_pos_pelkes SET nama_pos = 'Silo Sungai Pinang', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-27108';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Maranatha Karang Agung Tengah', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-56167';
UPDATE m_pos_pelkes SET nama_pos = 'Bakal Jemaat Sion Merlung', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-81626';
UPDATE m_pos_pelkes SET nama_pos = 'GPIB Pos Pelkes "Sumber Kasih" Kalampising', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-52165';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes "Sejahtera" Samboja', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-77457';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes "Torsina" Senipah', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-34993';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes "Efrata" Traktor VI', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-89558';
UPDATE m_pos_pelkes SET nama_pos = 'Bajem Maranatha Sebulu', kategori = 'Bajem' WHERE id_pos = 'POS-89562';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Sumber Hidup Sebamban', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-69232';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Air Hidup Seikotuk', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-25738';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Samaria Pelambaian', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-70577';
UPDATE m_pos_pelkes SET nama_pos = 'Marturia Sungai Uma', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-94758';
UPDATE m_pos_pelkes SET nama_pos = 'Anugerah Penabur Karang Agung', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-95716';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Maranatha Kelapa Kampit', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-97007';
UPDATE m_pos_pelkes SET nama_pos = 'Immanuel Bengkarek', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-51092';
UPDATE m_pos_pelkes SET nama_pos = 'Tuah Jubata Sei Pelaik', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-34433';
UPDATE m_pos_pelkes SET nama_pos = 'Sahabat Berinang', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-57892';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Perdamaian Km12 Bagan Musik Estate', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-39714';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Arai Kehidupan Air Mengaris', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-88810';
UPDATE m_pos_pelkes SET nama_pos = 'Bajem Tabanan', kategori = 'Bajem' WHERE id_pos = 'POS-38840';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Hosana Separi', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-36849';
UPDATE m_pos_pelkes SET nama_pos = 'Pos Pelkes Bukit Sion Giri Agung', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-35736';
UPDATE m_pos_pelkes SET nama_pos = 'Immanuel Mempawah', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-62914';
UPDATE m_pos_pelkes SET nama_pos = 'Kharisma Mundun', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-67834';
UPDATE m_pos_pelkes SET nama_pos = 'Tuah Petara Sintang', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-43392';
UPDATE m_pos_pelkes SET nama_pos = 'Ekklesia Nanga SIlat', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-19856';
UPDATE m_pos_pelkes SET nama_pos = 'Bethel Selabe', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-24342';
UPDATE m_pos_pelkes SET nama_pos = 'Alfa & Omega Ilai Pejugan', kategori = 'Pos Pelkes' WHERE id_pos = 'POS-41679';
UPDATE m_pos_pelkes SET nama_pos = 'Bajem SILOAM Binong', kategori = 'Bajem' WHERE id_pos = 'POS-34686';

-- 4. Update m_pendeta (cleaned names)
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Anita Angelina Lovica Putu Buraen, S.Si-Teol' WHERE id_pendeta = 'PDT-19060024';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Leo Nardo Pardosi, S. Si. Teol' WHERE id_pendeta = 'PDT-51107295';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Windy Untajana S.Si (Teol.)' WHERE id_pendeta = 'PDT-21159377';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Arni Muliyanti Mali, S.Th' WHERE id_pendeta = 'PDT-87216948';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Ben Bianco Pattinama, S.Si-Teol' WHERE id_pendeta = 'PDT-43300681';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Nadya Natalia Antoinette Gala, S. Th' WHERE id_pendeta = 'PDT-86990096';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Paulin Maureel Titiheru' WHERE id_pendeta = 'PDT-70501119';
UPDATE m_pendeta SET nama_lengkap = 'Pdt anithya Adriana Talakua Saragih' WHERE id_pendeta = 'PDT-32299530';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Otniel Jonatan Panjinegara Adua, S.Si. (Teol.)' WHERE id_pendeta = 'PDT-41915346';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Johnstevance Eldad Winman, S. Si-Teol' WHERE id_pendeta = 'PDT-82603338';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Putra Sang Bayu, S.Fil.' WHERE id_pendeta = 'PDT-37549598';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Josua Natal Walumbu' WHERE id_pendeta = 'PDT-26374165';
UPDATE m_pendeta SET nama_lengkap = 'Stephani Gratia Lalenoh S. Si-Teol' WHERE id_pendeta = 'PDT-92486233';
UPDATE m_pendeta SET nama_lengkap = 'Dania Ariskah, S.Th' WHERE id_pendeta = 'PDT-37149792';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Ananda Kezia br Sebayang, S.Th' WHERE id_pendeta = 'PDT-21939323';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Angelly Christisya Kantohe, M.Si' WHERE id_pendeta = 'PDT-64020785';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Reza Hariyoga, S.Si. (Teol.)' WHERE id_pendeta = 'PDT-59711512';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Maretha Kurnia Sari S. Si-Teol' WHERE id_pendeta = 'PDT-87046457';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Iunike Ribka Chrisna Pawestri, S.Si (Teol)' WHERE id_pendeta = 'PDT-39429573';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Adystia Ernel Raintung, S.Fil' WHERE id_pendeta = 'PDT-30098900';
UPDATE m_pendeta SET nama_lengkap = 'Rudolfo Jacob Manusiwa S.Si-Teol' WHERE id_pendeta = 'PDT-66495066';
UPDATE m_pendeta SET nama_lengkap = 'Meylisa Paulina Boesday, S.Th' WHERE id_pendeta = 'PDT-77965490';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Kevin Eflyano Badilo, S.Si.Teol' WHERE id_pendeta = 'PDT-57362747';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Rifensia Jeriska Soselisa' WHERE id_pendeta = 'PDT-29286934';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Giovanno Adi Nugroho, S.Si-Teol' WHERE id_pendeta = 'PDT-91423016';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Ni Gusti Ketut Melliana Achriyanthi Arnawa, S.Si-Teol' WHERE id_pendeta = 'PDT-94436290';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Yehezkiel Marselino Banjarnahor S.Fil' WHERE id_pendeta = 'PDT-19375058';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Trisa Angela Mauriza Sinaulan, S.Th' WHERE id_pendeta = 'PDT-34532604';
UPDATE m_pendeta SET nama_lengkap = 'Benoni Benyamin Klokke, S.Si-Teol.' WHERE id_pendeta = 'PDT-34880669';
UPDATE m_pendeta SET nama_lengkap = 'Pdt Mauren Astria Tatipatta, S.Th.' WHERE id_pendeta = 'PDT-70567471';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Cristin Dwi Ningsih, S.Si-Teol' WHERE id_pendeta = 'PDT-32051258';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Marchely Elvira Sirait -Ruitenbach, S. Si. Teol' WHERE id_pendeta = 'PDT-48212443';
UPDATE m_pendeta SET nama_lengkap = 'Nevada Florida Nualedang, Ssi.Teol' WHERE id_pendeta = 'PDT-56844638';
UPDATE m_pendeta SET nama_lengkap = 'Marena, S.Th' WHERE id_pendeta = 'PDT-97921792';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Fiola Aura Thahara, S. Si-Teol' WHERE id_pendeta = 'PDT-74312933';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Odi Etman Raidas Mali, S. Th' WHERE id_pendeta = 'PDT-26671820';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Mick Mordekhai Sopacoly, S.Th., M.Si.' WHERE id_pendeta = 'PDT-84971611';
UPDATE m_pendeta SET nama_lengkap = 'Alency Geovani Wijaya, S.Th' WHERE id_pendeta = 'PDT-84597888';
UPDATE m_pendeta SET nama_lengkap = 'Pdt Valini Mandaries Rompas, S.Th' WHERE id_pendeta = 'PDT-99170588';
UPDATE m_pendeta SET nama_lengkap = 'nuh gustomi gultom, S.Si-Teol' WHERE id_pendeta = 'PDT-92176638';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Akselofira Khidsal Dukhid, S.Si-Teol' WHERE id_pendeta = 'PDT-63921098';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Rafilius Ariyanto, S.Th' WHERE id_pendeta = 'PDT-39185836';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Corinthiani Perbina Sinulingga, S.Fil' WHERE id_pendeta = 'PDT-34353889';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Mega Amelia' WHERE id_pendeta = 'PDT-80027321';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Novita Sarah Wilhelmina Sumampow, S.Fil' WHERE id_pendeta = 'PDT-61800733';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Clinton Banjarnahor' WHERE id_pendeta = 'PDT-22062148';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Kezia Elza Bawole S.Th' WHERE id_pendeta = 'PDT-99011520';
UPDATE m_pendeta SET nama_lengkap = 'Nataniel Yeperson Blegur Ssi.Teol' WHERE id_pendeta = 'PDT-65727337';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Rani Natalia Br. SItorus S.Si-Teol' WHERE id_pendeta = 'PDT-97284701';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Joshua Hendrikson Siregar, S.Si-Teol' WHERE id_pendeta = 'PDT-50581483';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Stiven Kurniadijaya Lahunduitan Macpal, S.Si.Teol.' WHERE id_pendeta = 'PDT-17657741';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Genesya, M.Th.' WHERE id_pendeta = 'PDT-91784974';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Dressta Margareth Aksamine Titihalawa, S.Th.' WHERE id_pendeta = 'PDT-79598449';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Tien Apriani Djolawang, S.Th' WHERE id_pendeta = 'PDT-23285681';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Pit Manghophop Sitompul, S.Si-Teol' WHERE id_pendeta = 'PDT-71723244';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Geofani Febrian Ruindungan' WHERE id_pendeta = 'PDT-32980492';
UPDATE m_pendeta SET nama_lengkap = 'Kefi Putriani Banunu, S.Th' WHERE id_pendeta = 'PDT-75037916';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Roki Yunus, S.Si-Teol' WHERE id_pendeta = 'PDT-80598199';
UPDATE m_pendeta SET nama_lengkap = 'Tiffany Hillary Derek, S.Th' WHERE id_pendeta = 'PDT-70698942';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Samuel Roberto Lintang, S.Si-Teol' WHERE id_pendeta = 'PDT-73800812';
UPDATE m_pendeta SET nama_lengkap = 'Arfiando Rivaldo Aprilio Mekel, S.Fil' WHERE id_pendeta = 'PDT-59135418';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Richard Christov Lewerissa, S.Th,.' WHERE id_pendeta = 'PDT-33372790';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Chintia Oktavia, S.Fil' WHERE id_pendeta = 'PDT-91331801';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Maca Dina Vira Tarigan, S.Fil' WHERE id_pendeta = 'PDT-61105165';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Aditya Paschal Pantow, S.Si-Teol., M.Si' WHERE id_pendeta = 'PDT-50731837';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Celine Meirella Pesiwarissa, S. Si-Teol.' WHERE id_pendeta = 'PDT-75744712';
UPDATE m_pendeta SET nama_lengkap = 'Mauren Priscilla Agatha Latupeirissa M.Si' WHERE id_pendeta = 'PDT-63297445';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Gladys Marseline Wilhelmina Rompas, S.Si.Teol' WHERE id_pendeta = 'PDT-98564767';
UPDATE m_pendeta SET nama_lengkap = 'Devina Fenisia Larungkondo,S.Si. Teol' WHERE id_pendeta = 'PDT-43833673';
UPDATE m_pendeta SET nama_lengkap = 'DOROTHEA FEBE WINMAN, M.Si' WHERE id_pendeta = 'PDT-57348885';
UPDATE m_pendeta SET nama_lengkap = 'Yemmima Indri Thena Kartika, S. Fil' WHERE id_pendeta = 'PDT-43759100';
UPDATE m_pendeta SET nama_lengkap = 'Magiantang Regina Fransiska' WHERE id_pendeta = 'PDT-29777050';
UPDATE m_pendeta SET nama_lengkap = 'Lea Christty Barahama S.Si-Teol' WHERE id_pendeta = 'PDT-11639704';
UPDATE m_pendeta SET nama_lengkap = 'Yapia Amung' WHERE id_pendeta = 'PDT-50703951';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Fransleo Cornelis Melatunan Junior, S.Si Teol' WHERE id_pendeta = 'PDT-41950460';
UPDATE m_pendeta SET nama_lengkap = 'Benedictus Patriach Paskah Unpapar S.Fil' WHERE id_pendeta = 'PDT-78038857';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Yosua Asido Parulian Simbolon S. Fil' WHERE id_pendeta = 'PDT-27471110';
UPDATE m_pendeta SET nama_lengkap = 'Pendeta rut marchel avellia, S.Si Teol' WHERE id_pendeta = 'PDT-74857909';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Hezron Tangke Salu Pakan, S.Th' WHERE id_pendeta = 'PDT-23910877';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Valerie Estherlita Javelien Sumlang, S.Si (Teol)' WHERE id_pendeta = 'PDT-42480179';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Satius, S.Th' WHERE id_pendeta = 'PDT-64742682';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Antoneta Taneo, S.Th' WHERE id_pendeta = 'PDT-65676161';
UPDATE m_pendeta SET nama_lengkap = 'Kefi Putriani Banunu, S.Th' WHERE id_pendeta = 'PDT-50821277';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. ENOS ZURIEL HEHAKAJA, S.Si-Teol' WHERE id_pendeta = 'PDT-29746330';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Aninda Marlya Wangkay, S.Fil.' WHERE id_pendeta = 'PDT-63289176';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Aedelyn Sylvia Yunita Laiskodat S.Si- Teol' WHERE id_pendeta = 'PDT-16929588';
UPDATE m_pendeta SET nama_lengkap = 'Melinda Marpaung' WHERE id_pendeta = 'PDT-57897189';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Anthony Richard Pietersz, S.Si-Teol' WHERE id_pendeta = 'PDT-45846521';
UPDATE m_pendeta SET nama_lengkap = 'Pendeta Cyntia Nellyta, S. Si. Teol.' WHERE id_pendeta = 'PDT-37298708';
UPDATE m_pendeta SET nama_lengkap = 'Ruth Meilan Tupalessy, S.Si.(Teol)' WHERE id_pendeta = 'PDT-41129720';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Claudio Hersa Totonini Gurusinga, S.Si-Teol.' WHERE id_pendeta = 'PDT-47831495';
UPDATE m_pendeta SET nama_lengkap = 'Pdt Eunykhe Widiarty Nani, S. Th' WHERE id_pendeta = 'PDT-46514951';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Timotius Verdino, M.Fil.' WHERE id_pendeta = 'PDT-10651965';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Moshe William Daniel, S. Fil' WHERE id_pendeta = 'PDT-80271497';
UPDATE m_pendeta SET nama_lengkap = 'Pendeta Christy Febianty Sinaga - Lekahena' WHERE id_pendeta = 'PDT-52587201';
UPDATE m_pendeta SET nama_lengkap = 'Pdt Asina Wahyu Deinnara S.Si Teol' WHERE id_pendeta = 'PDT-71887759';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Gabriella Christianty Titahena' WHERE id_pendeta = 'PDT-59630925';
UPDATE m_pendeta SET nama_lengkap = 'Shendy Novaldy Sitania, S. Si-Teol, M.Sc' WHERE id_pendeta = 'PDT-81550253';
UPDATE m_pendeta SET nama_lengkap = 'LESMA RIANTI SIMANJUNTAK S.Si Teol' WHERE id_pendeta = 'PDT-40606621';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Ade Rindunta' WHERE id_pendeta = 'PDT-47079836';
UPDATE m_pendeta SET nama_lengkap = 'Pdt. Ezra Sudarsono, S.Si., M.M.' WHERE id_pendeta = 'PDT-21698587';

-- 5. Insert/Update KMJs from Jemaat.txt into m_pendeta & m_jemaat_induk
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-01-01-AP', '01-01-AP', 'Pdt. Vanezza Albertina Siahaya', '+62 812 1941 1525', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-01-01-AP' WHERE id_induk = '01-01-AP';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-01-06-MP', '01-06-MP', 'Pdt. Julianus Yermias Kaimarehe', '+62 813 5143 6663', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-01-06-MP' WHERE id_induk = '01-06-MP';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-04-10-IP', '04-10-IP', 'Abraham Ferdinandus', '+62 812 8879 2585', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-04-10-IP' WHERE id_induk = '04-10-IP';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-04-04-BZ', '04-04-BZ', 'Pdt. Margaretha Dolf-Pelealu', '+62 813 6632 8883', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-04-04-BZ' WHERE id_induk = '04-04-BZ';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-04-06-EP', '04-06-EP', 'Pdt. Immanuel C. Nugroho', '+62 812 8001 8376', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-04-06-EP' WHERE id_induk = '04-06-EP';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-04-07-EF', '04-07-EF', 'Pdt. Sonya Alvie Umkeketony, S.Si - Teol', '+62 822 2701 2363', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-04-07-EF' WHERE id_induk = '04-07-EF';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-04-08-ED', '04-08-ED', 'Pdt. Sandino', '+62 851 0155 3028', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-04-08-ED' WHERE id_induk = '04-08-ED';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-04-09-GR', '04-09-GR', 'Pdt. Patricia Lisa Syaranamual, S.Th.', '+62 822 8689 7979', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-04-09-GR' WHERE id_induk = '04-09-GR';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-04-15-SD', '04-15-SD', 'Pdt. Wita Atria Akihary-Paputungan', NULL, 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-04-15-SD' WHERE id_induk = '04-15-SD';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-03-05-ET', '03-05-ET', 'Pdt. Melky Patoni', '+62 822 9302 4024', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-03-05-ET' WHERE id_induk = '03-05-ET';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-03-07-IB', '03-07-IB', 'Ronald Octavian  Rampala', '+62 878 8921 7297', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-03-07-IB' WHERE id_induk = '03-07-IB';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-05-07-PS', '05-07-PS', 'Pdt. YOHANES POSMAN ZAI, S.Si-Teol', '+62 821 5712 3802', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-05-07-PS' WHERE id_induk = '05-07-PS';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-05-06MJ', '05-06MJ', 'Willem Esau Talakua', '+62 812 9894 4310', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-05-06MJ' WHERE id_induk = '05-06MJ';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-05-01-AJ', '05-01-AJ', 'Pdt. Samuel Natar, M.Th', '+62 812 8827 586', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-05-01-AJ' WHERE id_induk = '05-01-AJ';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-05-10-EJ', '05-10-EJ', 'Pdt. Novianti Situmorang', '+62 895 3699 08383', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-05-10-EJ' WHERE id_induk = '05-10-EJ';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-05-01-IJ', '05-01-IJ', 'Pdt. Rio Andre Kolinug, S.Si-Teol', '+62 838 9070 7728', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-05-01-IJ' WHERE id_induk = '05-01-IJ';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-02-01-BM', '02-01-BM', 'Pdt. Delila Benu', '+62 822 3346 4104', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-02-01-BM' WHERE id_induk = '02-01-BM';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-02-04-IT', '02-04-IT', 'Pdt. Berillos A H Panggabean', '+62 813 4960 6553', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-02-04-IT' WHERE id_induk = '02-04-IT';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-02-05-KM', '02-05-KM', 'Pdt Egla Bontor Irnahasri Nababan, S. Si. Teol', '+62 812 8235 0574', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-02-05-KM' WHERE id_induk = '02-05-KM';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-06-05-MA', '06-05-MA', 'Pdt. Deasy E. Wattimena-Kalalo', '+62 812 8001 2076', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-06-05-MA' WHERE id_induk = '06-05-MA';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-06-03-IM', '06-03-IM', 'Pdt. Adventino Ekaristi Priyonggo', '+62 813 4725 2770', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-06-03-IM' WHERE id_induk = '06-03-IM';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-06-07-PE', '06-07-PE', 'Pdt. Leoni Prameswari, S.Si-Teol', '+62 813 4000 4142', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-06-07-PE' WHERE id_induk = '06-07-PE';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-06-12-SP', '06-12-SP', 'Pdt. Marco Yoel Kumendong, S.Th', '+62 852 4619 7020', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-06-12-SP' WHERE id_induk = '06-12-SP';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-06-13-MK', '06-13-MK', 'Pdt. Heber Hutauruk', '+62 821 1134 0689', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-06-13-MK' WHERE id_induk = '06-13-MK';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-07-09-YU', '07-09-YU', 'Pdt. Albert Wowor, S.Th.', '+62 813 4193 6890', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-07-09-YU' WHERE id_induk = '07-09-YU';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-16-10-PS', '16-10-PS', 'Pdt. Lefijandie R. J. Kembuan', '+62 812 4115 8751', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-16-10-PS' WHERE id_induk = '16-10-PS';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-16-14-TS', '16-14-TS', 'Pdt. Claudya I. Yosep - Sahertian', '+62 852 4515 3728', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-16-14-TS' WHERE id_induk = '16-14-TS';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-18-04-MD', '18-04-MD', 'Pendeta Sonya Medyarto - Sitaniapessy', '+62 812 9932 973', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-18-04-MD' WHERE id_induk = '18-04-MD';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-20-13-SP', '20-13-SP', 'Ridwan Hamonangan Purba', NULL, 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-20-13-SP' WHERE id_induk = '20-13-SP';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-20-01-AB', '20-01-AB', 'Pdt. Vika Manuela Ferdinandus', '+62 852 1238 1222', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-20-01-AB' WHERE id_induk = '20-01-AB';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-20-02-BM', '20-02-BM', 'Pdt. Johanes Aldo Lampus, S. Si-Teol', '+62 821 1529 5708', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-20-02-BM' WHERE id_induk = '20-02-BM';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-20-21-S', '20-21-S', 'Pdt. Oktaviyan Sopater Silahooij, S.Si Teol', '+62 878 8192 0720', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-20-21-S' WHERE id_induk = '20-21-S';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-20-03-BP', '20-03-BP', 'Pdt. Ribka Atviani, S.Si.Teol.', '+62 813 6765 1979', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-20-03-BP' WHERE id_induk = '20-03-BP';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-20-15-BA', '20-15-BA', 'Pdt. Jebelino Adiputra Kastanya, S.Si.Teol', NULL, 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-20-15-BA' WHERE id_induk = '20-15-BA';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-20-04-EK', '20-04-EK', 'Pdt. Christian Talutu', '+62 821 1399 6643', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-20-04-EK' WHERE id_induk = '20-04-EK';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-20-16-EA', '20-16-EA', 'Pdt. David Cornelius Sihombing, S.Si-Teol', '+62 812 6438 2193', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-20-16-EA' WHERE id_induk = '20-16-EA';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-20-05-IT', '20-05-IT', 'Pdt. Elphano Risdo Souisa, S. Th', '+62 822 4615 8960', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-20-05-IT' WHERE id_induk = '20-05-IT';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-20-19-S', '20-19-S', 'Pdt. Agus Prasetyo Milono', '+62 812 6968 4958', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-20-19-S' WHERE id_induk = '20-19-S';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-20-07-MS', '20-07-MS', 'Pdt DR Abraham Silo Wilar, M.Th, M.A', NULL, 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-20-07-MS' WHERE id_induk = '20-07-MS';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-20-08-MI', '20-08-MI', 'Pdt. Amanda Lekahena, S.Si-Teol', '+62 822 2551 0885', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-20-08-MI' WHERE id_induk = '20-08-MI';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-20-09-OS', '20-09-OS', 'Pdt. Novayanti Astrid Pattikawa-Lambey', '+62 822 8821 4961', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-20-09-OS' WHERE id_induk = '20-09-OS';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-20-10-PA', '20-10-PA', 'Pdt. Sarinah Allo Layuk', '+62 852 1558 6202', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-20-10-PA' WHERE id_induk = '20-10-PA';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-20-11-SS', '20-11-SS', 'Pdt. VEGA LAPIAN - SARASAK, S. Th', '+62 812 8449 5259', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-20-11-SS' WHERE id_induk = '20-11-SS';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-20-12-SK', '20-12-SK', 'Pdt. Jani Victor Karatem', '+62 813 2546 4855', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-20-12-SK' WHERE id_induk = '20-12-SK';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-20-22-BZ', '20-22-BZ', 'Pdt. Victoriana Desmatrusia Resdawati, S.Th.', '+62 852 5240 3919', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-20-22-BZ' WHERE id_induk = '20-22-BZ';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-20-24-PJ', '20-24-PJ', 'Pdt. Ergon Pranata Pieters, M.Th', '+62 856 9754 2017', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-20-24-PJ' WHERE id_induk = '20-24-PJ';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-21-02-RP', '21-02-RP', 'Pdt. Samrut Peloa', '+62 812 4803 8484', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-21-02-RP' WHERE id_induk = '21-02-RP';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-21-04-IK', '21-04-IK', 'Pdt. Rocky Samuel Karenda', '+62 811 1004 768', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-21-04-IK' WHERE id_induk = '21-04-IK';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-21-06-SB', '21-06-SB', 'Pdt. Sergio Souisa', '+62 821 2171 7603', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-21-06-SB' WHERE id_induk = '21-06-SB';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-22-08-MB', '22-08-MB', 'Pdt nelce alelo', NULL, 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-22-08-MB' WHERE id_induk = '22-08-MB';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-22-04-EB', '22-04-EB', 'Pdt. Theofonslow Trifosa Omega Salouw, S.Th', '+62 853 9562 9758', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-22-04-EB' WHERE id_induk = '22-04-EB';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-22-07-KK', '22-07-KK', 'Pdt. Dr. Stella Yessy Exlentya Pattipeilohy, S.Si-Teol., M.Th.', '+62 812 2870 1060', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-22-07-KK' WHERE id_induk = '22-07-KK';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-22-11-SB', '22-11-SB', 'Pdt. Margaretha Kamban', '+62 813 2060 1152', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-22-11-SB' WHERE id_induk = '22-11-SB';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-23-06-IS', '23-06-IS', 'Pdt. Elly Dominggas Pitoy - de Bell', '+62 818 7104 16', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-23-06-IS' WHERE id_induk = '23-06-IS';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-23-02-ES', '23-02-ES', '"Pdt. Fenovri Setyasusanto Satata', ': "', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-23-02-ES' WHERE id_induk = '23-02-ES';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-23-03-ET', '23-03-ET', 'Pdt. Feggy M. Salindeho-Beslar', '+62 813 7892 9991', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-23-03-ET' WHERE id_induk = '23-03-ET';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-23-14-HS', '23-14-HS', 'Pdt. Candra N. K. Ch. Wila, S.Si-Teol', '+62 813 4661 6727', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-23-14-HS' WHERE id_induk = '23-14-HS';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-23-08-PS', '23-08-PS', 'Pdt. Frenky Vinsentius Latuihamallo, M.Si.', '+62 822 2535 9307', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-23-08-PS' WHERE id_induk = '23-08-PS';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-23-11-SK', '23-11-SK', 'Pdt. Frengky Iverson Manenat Tacoy, S.Si-Teol', '+62 852 3222 4953', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-23-11-SK' WHERE id_induk = '23-11-SK';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-24-05-MT', '24-05-MT', 'Pdt. Septy Berpras Lillung-Sir, S.Si-Teol', '+62 812 3210 0944', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-24-05-MT' WHERE id_induk = '24-05-MT';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-23-05-IA', '23-05-IA', 'Pdt. Timotius Eduard Lalala, S.Si.Teol.', '+62 822 5569 1124', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-23-05-IA' WHERE id_induk = '23-05-IA';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-24-06-SN', '24-06-SN', 'Pdt. Meryani fedrika gimon', '+62 813 2643', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-24-06-SN' WHERE id_induk = '24-06-SN';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-24-08-SI', '24-08-SI', 'Pdt. Olivia G. Siura-Salu', '+62 812 8702 2316', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-24-08-SI' WHERE id_induk = '24-08-SI';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-19-14-PB', '19-14-PB', 'Pdt. Dominggus Andreas Boesday', '+62 812 3136 8424', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-19-14-PB' WHERE id_induk = '19-14-PB';
INSERT INTO m_pendeta (id_pendeta, id_induk, nama_lengkap, no_wa, jabatan, is_kmj, is_pj) VALUES ('PDT-KMJ-19-17-SK', '19-17-SK', 'Pdt. Jovina Hutahaean - Luntungan', '+62 823 5216 8608', 'KMJ', TRUE, FALSE) ON CONFLICT (id_pendeta) DO UPDATE SET id_induk = EXCLUDED.id_induk, is_kmj = TRUE;
UPDATE m_jemaat_induk SET id_kmj = 'PDT-KMJ-19-17-SK' WHERE id_induk = '19-17-SK';

COMMIT;
